services:

  postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tere123
      POSTGRES_DB: tfgUO294178_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/sql:/docker-entrypoint-initdb.d

  backend:
    build: ./backend

    ports:
      - "3000:3000"

    environment:
      DB_USER: postgres
      DB_PASSWORD: tere123
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tfgUO294178_db

      SESSION_SECRET: tfg_uo294178_secret

      PORT: 3000
      NODE_ENV: development
      FRONTEND_URL: http://localhost:4200

    depends_on:
      - postgres

  frontend:
    build: ./frontend

    ports:
      - "4200:4200"

    depends_on:
      - backend

volumes:
  postgres_data:
  